"""Build and check the M6 glossary (docs/progress/1.0/glossary/).

Usage:
  python docs/progress/1.0/glossary/build.py --render --browser <chromium>   render diagrams/*.mmd to SVG with the
                                                                           local Mermaid CLI, then write the page
  python docs/progress/1.0/glossary/build.py                                 write glossary.md from terms.json only
  python docs/progress/1.0/glossary/build.py --check                         verify without writing (no browser needed)

`terms.json` is the editable source of the terms; `diagrams/<id>.mmd` is the editable source of each diagram.
`diagrams/manifest.json` records, for every diagram, the SHA-256 of its source and of its rendered SVG, the
Mermaid CLI version and the production command. `--check` fails when a term lacks a field, a level or a diagram,
when a source or SVG digest differs from the manifest, or when glossary.md differs from what terms.json produces.
Standard library only; rendering needs the approved Mermaid CLI under tools/node/mermaid-cli.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parents[3]
DIAGRAMS = HERE / "diagrams"
MANIFEST = DIAGRAMS / "manifest.json"
PAGE = HERE / "glossary.md"
TERMS = HERE / "terms.json"
CONFIG = HERE / "mermaid.json"
MMDC = ROOT / "tools/node/mermaid-cli/node_modules/.bin/mmdc"
FIELDS = ("id", "term", "level", "definition", "ui", "source")
COMMAND = "mmdc -q -p <puppeteer config> -c docs/progress/1.0/glossary/mermaid.json -i diagrams/<id>.mmd -o diagrams/<id>.svg"


def sha(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load() -> dict:
    return json.loads(TERMS.read_text(encoding="utf-8"))


def term_errors(doc: dict) -> list[str]:
    errors, seen = [], set()
    levels = {lv["id"] for lv in doc.get("levels", [])}
    for t in doc.get("terms", []):
        tid = t.get("id", "?")
        for f in FIELDS:
            if not isinstance(t.get(f), str) or not t[f].strip():
                errors.append(f"{tid}: missing '{f}'")
        if tid in seen:
            errors.append(f"{tid}: duplicate id")
        seen.add(tid)
        if t.get("level") not in levels:
            errors.append(f"{tid}: unknown level {t.get('level')!r}")
        if not (DIAGRAMS / f"{tid}.mmd").is_file():
            errors.append(f"{tid}: no diagram source diagrams/{tid}.mmd")
    names = [t.get("term", "").lower() for t in doc.get("terms", [])]
    for n in {n for n in names if names.count(n) > 1}:
        errors.append(f"term '{n}' is defined twice")
    return errors


def page(doc: dict) -> str:
    out = ["# Glossary (M6)", "",
           "Status: **draft for stage 2.** Generated by `build.py` from `terms.json`; edit the sources, not this page. "
           "One term per concept (charter M1). Each term enters at the learning level where it is first needed (charter M6, D7). "
           "The levels follow the steps of the [solving workflow](../solving-workflow.md) and are provisional until the owner "
           "decides the learning path; the UI locations are the planned surfaces of solving-workflow section 4, not a layout. "
           "Diagrams are rendered locally with the Mermaid CLI; sources and digests are in `diagrams/`.", ""]
    out += ["## Levels", "", "| Level | Name | Workflow step |", "|---|---|---|"]
    out += [f"| {lv['id']} | {lv['name']} | {lv['workflow']} |" for lv in doc["levels"]]
    for lv in doc["levels"]:
        out += ["", f"## {lv['id']}: {lv['name']}"]
        for t in sorted((t for t in doc["terms"] if t["level"] == lv["id"]), key=lambda t: t["term"].lower()):
            out += ["", f"### {t['term']}", "", t["definition"], "",
                    f"![{t['term']}](diagrams/{t['id']}.svg)", "",
                    f"- First needed: {lv['id']} ({lv['name']})",
                    f"- In the UI: {t['ui']}",
                    f"- Source: {t['source']}"]
    return "\n".join(out) + "\n"


def render(doc: dict, browser: str) -> None:
    version = subprocess.run([str(MMDC), "--version"], capture_output=True, text=True, check=True).stdout.strip()
    with tempfile.TemporaryDirectory() as tmp:
        cfg = Path(tmp) / "puppeteer.json"
        cfg.write_text(json.dumps({"executablePath": browser, "args": ["--no-sandbox"]}), encoding="utf-8")
        entries = {}
        for t in doc["terms"]:
            src, svg = DIAGRAMS / f"{t['id']}.mmd", DIAGRAMS / f"{t['id']}.svg"
            subprocess.run([str(MMDC), "-q", "-p", str(cfg), "-c", str(CONFIG), "-i", str(src), "-o", str(svg)], check=True)
            entries[t["id"]] = {"source_sha256": sha(src), "svg_sha256": sha(svg)}
    MANIFEST.write_text(json.dumps({"tool": "@mermaid-js/mermaid-cli", "version": version, "config_sha256": sha(CONFIG),
                                    "command": COMMAND, "diagrams": entries}, indent=1, sort_keys=True) + "\n",
                        encoding="utf-8")


def check(doc: dict) -> list[str]:
    errors = term_errors(doc)
    try:
        man = json.loads(MANIFEST.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        return errors + [f"manifest: cannot read ({exc})"]
    if man.get("config_sha256") != sha(CONFIG):
        errors.append("manifest: mermaid.json changed since rendering")
    ids = {t.get("id") for t in doc.get("terms", [])}
    if set(man.get("diagrams", {})) != ids:
        errors.append("manifest: diagram set differs from the terms")
    for tid, e in man.get("diagrams", {}).items():
        src, svg = DIAGRAMS / f"{tid}.mmd", DIAGRAMS / f"{tid}.svg"
        if not src.is_file() or sha(src) != e.get("source_sha256"):
            errors.append(f"{tid}: diagram source changed since rendering")
        if not svg.is_file() or sha(svg) != e.get("svg_sha256"):
            errors.append(f"{tid}: SVG missing or differs from the manifest")
    if not PAGE.is_file() or PAGE.read_text(encoding="utf-8") != page(doc):
        errors.append("glossary.md is not the output of terms.json; run build.py")
    return errors


def main(argv: list[str]) -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--render", action="store_true")
    ap.add_argument("--browser")
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args(argv)
    doc = load()
    if a.check:
        errors = check(doc)
        for e in errors:
            print(e)
        if not errors:
            print(f"glossary: ok ({len(doc['terms'])} terms)")
        return 1 if errors else 0
    errors = term_errors(doc)
    if errors:
        print("\n".join(errors))
        return 1
    if a.render:
        if not a.browser:
            ap.error("--render needs --browser <path to a local Chromium>")
        render(doc, a.browser)
    PAGE.write_text(page(doc), encoding="utf-8")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
