"""Write dispositions.md from the six shard files.

  python docs/progress/1.0/dispositions/build_report.py

Fails when check_dispositions.py --all fails. Running it twice gives
byte-identical output.
"""
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
import check_dispositions as cd  # noqa: E402

ORDER = cd.DISPOSITIONS


def _kinds(rows, group):
    return {d["disposition"] for u in group for _, d, _ in cd.decisions(rows[u])}


def _mixed(kinds):
    """Delete against any retained purpose, or automate against keep or redesign."""
    return ("delete" in kinds and kinds & set(cd.RETAINED)) or ("automate" in kinds and kinds & {"keep", "redesign"})


def _cell(text):
    return " ".join(str(text).split()).replace("|", "\\|")


def purpose_groups(rows):
    parent = {u: u for u in rows}

    def find(x):
        while parent[x] != x:
            parent[x] = parent[parent[x]]
            x = parent[x]
        return x

    for uid, row in rows.items():
        for other in row["same_purpose_as"]:
            if other in parent:
                a, b = find(uid), find(other)
                if a != b:
                    parent[max(a, b)] = min(a, b)
    groups = defaultdict(list)
    for u in rows:
        groups[find(u)].append(u)
    return [sorted(g) for g in groups.values() if len(g) > 1]


def render(units, flows, rows):
    out = ["# Stage 2.2 dispositions", "",
           "Generated by `build_report.py` from `dispositions-s1.json` to `-s6.json`; do not edit. Method: [README](README.md).", "",
           "Status: **draft for the owner.** The owner signs every `delete` and `automate` row (charter section 3); until then they are proposals.", ""]
    out += ["## Counts", "", "Decisions per shard; a split unit counts once per part.", "",
            "| Shard | " + " | ".join(ORDER) + " | decisions |", "|---|" + "---|" * (len(ORDER) + 1)]
    total = Counter()
    for n in range(1, 7):
        c = Counter(d["disposition"] for u, r in rows.items() if units[u]["shard"] == f"s{n}" for _, d, _ in cd.decisions(r))
        total += c
        out.append(f"| s{n} | " + " | ".join(str(c[d]) for d in ORDER) + f" | {sum(c.values())} |")
    out.append("| all | " + " | ".join(str(total[d]) for d in ORDER) + f" | {sum(total.values())} |")
    out += ["", "## For the owner's signature: delete and automate", "",
            "| Unit | Disposition | Function | Purpose | Reason | Same purpose as |", "|---|---|---|---|---|---|"]
    for uid in sorted(rows):
        r = rows[uid]
        for label, d, part_rows in cd.decisions(r):
            if d["disposition"] in ("delete", "automate"):
                what = "; ".join(units[uid]["names"]) + (f" (rows {', '.join(part_rows)})" if part_rows else "")
                out.append(f"| {label} | {d['disposition']} | {_cell(what)} | {_cell(d['purpose'])} | {_cell(d['reason'])} | {', '.join(r['same_purpose_as']) or '-'} |")
    out += ["", "## Purpose groups with mixed dispositions", "",
            "Units that share a purpose across layers (`same_purpose_as`). A group is listed for the integrator's check when it mixes `delete` with any disposition that keeps the purpose, or `automate` with `keep` or `redesign`; layers may differ legitimately (an engine function kept, its 0.4 button redesigned).", ""]
    mixed = [g for g in purpose_groups(rows) if _mixed(_kinds(rows, g))]
    if not mixed:
        out.append("- none")
    for g in mixed:
        out.append("- " + ", ".join(f"{u} {'/'.join(sorted(_kinds(rows, [u])))}" for u in g))
    out += ["", "## Flows", "", "| Flow | Units | Title |", "|---|---|---|"]
    per_flow = Counter(f for r in rows.values() for _, d, _ in cd.decisions(r) for f in d["flows"])
    for f in flows:
        out.append(f"| {f['id']} | {per_flow[f['id']]} | {_cell(f['title'])} |")
    unused = sorted(label for u, r in rows.items() for label, d, _ in cd.decisions(r) if not d["flows"])
    out += ["", f"Decisions serving no flow: {len(unused)} (all `delete` or `automate`).", ""]
    out += ["## All units", "", "| Unit | Disposition | Function | Flows | Requirements | Reason |", "|---|---|---|---|---|---|"]
    for uid in sorted(rows):
        r = rows[uid]
        for label, d, part_rows in cd.decisions(r):
            what = "; ".join(units[uid]["names"]) + (f" (rows {', '.join(part_rows)})" if part_rows else "")
            out.append(f"| {label} | {d['disposition']} | {_cell(what)} | {', '.join(d['flows']) or '-'} | {_cell('; '.join(d['requirements'])) or '-'} | {_cell(d['reason'])} |")
    return "\n".join(out) + "\n"


def main():
    units = {u["id"]: u for u in cd._load(HERE / "units.json")["units"]}
    flows = cd._load(HERE / "flows.json")["flows"]
    errors, rows = cd.check_all(units, {f["id"] for f in flows})
    if errors:
        for e in errors:
            print(e)
        return 1
    (HERE / "dispositions.md").write_text(render(units, flows, rows), encoding="utf-8", newline="\n")
    print(f"dispositions.md: {len(rows)} units")
    return 0


if __name__ == "__main__":
    sys.exit(main())
